services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - DB_data:/data/db

  backend:
    build: .
    ports:
      - 5000:3000
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/auth_playground
    depends_on:
      - mongo

volumes:
  DB_data:
